#!/usr/bin/env bash

# ver=843
# for i in $(seq 0 9); do
  # scripts/sigr python -m sigr.app inter --log log --snapshot model --root .cache/sigr-inter-augscale-adabn-$i-v$ver --fold $i --batch-size 900 --num-pixel 2 --num-filter 16 --adabn --minibatch --random-scale 1
# done
# ver=868
# for i in $@; do
  # scripts/sigr python -m sigr.app inter --log log --snapshot model --root .cache/sigr-inter-w150-lstm-adabn-$i-v$ver --fold $i --batch-size 180 --num-pixel 2 --num-filter 16 --adabn --minibatch --window 150 --adabn-num-epoch 10 --num-epoch 10 --lr-step 4 --lr-step 8 --lstm --lstm-last --lstm-dropout 0.5
# done
# ver=924
# for i in $@; do
  # scripts/sigr python -m sigr.app inter --log log --snapshot model --root .cache/sigr-inter-w150-lstm-adabn-$i-v$ver --fold $i --batch-size 900 --num-pixel 2 --num-filter 16 --adabn --window 150 --lstm-window 5 --num-adabn-epoch 1 --lstm --minibatch --num-lstm-hidden 128 --lstm-last 1 --lstm-dropout 0.5
# done
# ver=934
# for i in $@; do
  # scripts/sigr python -m sigr.app inter --log log --snapshot model --root .cache/sigr-inter-calib-w150-faug-lstm-adabn-$i-v$ver --fold $i --batch-size 1000 --num-pixel 2 --num-filter 16 --window 150 --lstm-window 15 --num-adabn-epoch 1 --lstm --num-lstm-hidden 16 --lstm-last 1 --lstm-dropout 0.5 --only-calib --params .cache/sigr-inter-w150-lstm-adabn-$i-v927/model-0060.params --adabn --faug 0.5
# done
# ver=937
# for i in $@; do
  # scripts/sigr python -m sigr.app inter --log log --snapshot model --root .cache/sigr-inter-calib-w150-faug-lstm-adabn-$i-v$ver --fold $i --batch-size 1000 --num-pixel 2 --num-filter 16 --window 150 --lstm-window 15 --num-adabn-epoch 1 --lstm --num-lstm-hidden 16 --lstm-last 1 --lstm-dropout 0.5 --only-calib --params .cache/sigr-inter-w150-lstm-adabn-$i-v927/model-0060.params --adabn --lr 0.01 --faug 1
# done
# ver=955.70
# for i in $@; do
  # scripts/sigr python -m sigr.app inter --log log --snapshot model --root .cache/sigr-inter-adabn-$i-v$ver --fold $i --batch-size 900 --adabn --minibatch --pixel-reduce-smooth --pixel-reduce-loss-weight 900
# done

# ver=957.50
# for i in $(seq 0 9); do
  # scripts/sigr python -m sigr.app exp --log log --snapshot model \
    # --num-epoch 28 --lr-step 16 --lr-step 24 --snapshot-period 28 \
    # --root .cache/sigr-csl-universal-intra-session-$i-v$ver \
    # --num-semg-row 24 --num-semg-col 7 \
    # --batch-size 2500 --decay-all --adabn --minibatch --dataset csl \
    # --preprocess '(csl-bandpass,csl-cut,downsample-5,median)' \
    # --balance-gesture 1 \
    # crossval --crossval-type universal-intra-session --fold $i
# done
# ver=957.51
# for i in $(seq 0 249); do
  # scripts/sigr python -m sigr.app exp --log log --snapshot model \
    # --num-epoch 14 --lr-step 8 --lr-step 12 --snapshot-period 14 \
    # --root .cache/sigr-csl-intra-session-$i-v$ver \
    # --num-semg-row 24 --num-semg-col 7 \
    # --batch-size 1000 --decay-all --adabn --num-adabn-epoch 10 --dataset csl \
    # --preprocess '(csl-bandpass,csl-cut,median)' \
    # --balance-gesture 1 \
    # --params .cache/sigr-csl-universal-intra-session-$(($i % 10))-v957.50/model-0028.params \
    # crossval --crossval-type intra-session --fold $i
# done

ver=958.16
for i in 0; do
  scripts/sigr python -m sigr.app exp --log log --snapshot model \
    --num-epoch 28 --lr-step 16 --lr-step 24 --snapshot-period 28 \
    --root .cache/sigr-ninapro-db1-universal-one-fold-intra-subject-$i-v$ver \
    --num-semg-row 1 --num-semg-col 10 \
    --batch-size 1000 --decay-all --dataset ninapro-db1 \
    --num-filter 64 \
    crossval --crossval-type universal-one-fold-intra-subject --fold $i
done
ver=958.16.1
for i in $(seq 0 26 | shuf); do
  scripts/sigr python -m sigr.app exp --log log --snapshot model \
    --num-epoch 28 --lr-step 16 --lr-step 24 --snapshot-period 28 \
    --root .cache/sigr-ninapro-db1-one-fold-intra-subject-$i-v$ver \
    --num-semg-row 1 --num-semg-col 10 \
    --batch-size 1000 --decay-all --dataset ninapro-db1 \
    --num-filter 64 \
    --params .cache/sigr-ninapro-db1-universal-one-fold-intra-subject-0-v958.16/model-0028.params \
    crossval --crossval-type one-fold-intra-subject --fold $i
done

ver=958.17
for i in $(seq 0 4 | shuf); do
  scripts/sigr python -m sigr.app exp --log log --snapshot model \
    --num-epoch 28 --lr-step 16 --lr-step 24 --snapshot-period 28 \
    --root .cache/sigr-universal-inter-session-$i-v$ver \
    --num-semg-row 24 --num-semg-col 7 \
    --batch-size 1000 --decay-all --dataset csl \
    --preprocess '(csl-bandpass,csl-cut,downsample-5,median)' \
    --balance-gesture 1 \
    --num-filter 64 \
    crossval --crossval-type universal-inter-session --fold $i
done
ver=958.17.1
for i in $(seq 0 24 | shuf); do
  scripts/sigr python -m sigr.app exp --log log --snapshot model \
    --num-epoch 28 --lr-step 16 --lr-step 24 --snapshot-period 28 \
    --root .cache/sigr-csl-inter-session-$i-v$ver \
    --num-semg-row 24 --num-semg-col 7 \
    --batch-size 1000 --decay-all --dataset csl \
    --preprocess '(csl-bandpass,csl-cut,median)' \
    --balance-gesture 1 \
    --params .cache/sigr-universal-inter-session-$(($i % 5))-v958.17/model-0028.params \
    --num-filter 64 \
    crossval --crossval-type inter-session --fold $i
done

ver=958.18
for i in $(seq 0 9 | shuf); do
  scripts/sigr python -m sigr.app exp --log log --snapshot model \
    --num-epoch 28 --lr-step 16 --lr-step 24 --snapshot-period 28 \
    --root .cache/sigr-csl-universal-intra-session-$i-v$ver \
    --num-semg-row 24 --num-semg-col 7 \
    --batch-size 2500 --decay-all --adabn --minibatch --dataset csl \
    --preprocess '(csl-bandpass,csl-cut,downsample-5,median)' \
    --balance-gesture 1 \
    --num-filter 64 \
    --num-pixel 0 \
    crossval --crossval-type universal-intra-session --fold $i
done
ver=958.18.1
for i in $(seq 0 249 | shuf); do
  scripts/sigr python -m sigr.app exp --log log --snapshot model \
    --num-epoch 14 --lr-step 8 --lr-step 12 --snapshot-period 14 \
    --root .cache/sigr-csl-intra-session-$i-v$ver \
    --num-semg-row 24 --num-semg-col 7 \
    --batch-size 1000 --decay-all --adabn --num-adabn-epoch 10 --dataset csl \
    --preprocess '(csl-bandpass,csl-cut,median)' \
    --balance-gesture 1 \
    --params .cache/sigr-csl-universal-intra-session-$(($i % 10))-v958.18/model-0028.params \
    --num-filter 64 \
    --num-pixel 0 \
    crossval --crossval-type intra-session --fold $i
done

ver=958.19
for i in $(seq 0 9 | shuf); do
  scripts/sigr python -m sigr.app exp --log log --snapshot model \
    --num-epoch 28 --lr-step 16 --lr-step 24 --snapshot-period 28 \
    --root .cache/sigr-csl-universal-intra-session-$i-v$ver \
    --num-semg-row 24 --num-semg-col 7 \
    --batch-size 2500 --decay-all --adabn --minibatch --dataset csl \
    --preprocess '(csl-bandpass,csl-cut,downsample-5,median)' \
    --balance-gesture 1 \
    --num-filter 64 \
    --num-pixel 0 --num-conv 4 \
    crossval --crossval-type universal-intra-session --fold $i
done
ver=958.19.1
for i in $(seq 0 249 | shuf); do
  scripts/sigr python -m sigr.app exp --log log --snapshot model \
    --num-epoch 14 --lr-step 8 --lr-step 12 --snapshot-period 14 \
    --root .cache/sigr-csl-intra-session-$i-v$ver \
    --num-semg-row 24 --num-semg-col 7 \
    --batch-size 1000 --decay-all --adabn --num-adabn-epoch 10 --dataset csl \
    --preprocess '(csl-bandpass,csl-cut,median)' \
    --balance-gesture 1 \
    --params .cache/sigr-csl-universal-intra-session-$(($i % 10))-v958.19/model-0028.params \
    --num-filter 64 \
    --num-pixel 0 --num-conv 4 \
    crossval --crossval-type intra-session --fold $i
done
