#!/usr/bin/env bash

# ver=512
# for i in 5 6 9; do
  # scripts/sigr python -m sigr.app inter --gpu 0 --gpu 1 --log log --snapshot model --root .cache/sigr-inter-adabn-tzeng-$i-v$ver --fold $i --adabn --batch-size 1800 --num-pixel 2 --num-filter 16 --tzeng --subject-loss-weight 0.1 --subject-confusion-loss-weight 0.1 --lambda-scale 1 --num-subject-block 0 --minibatch  --params .cache/sigr-inter-adabn-$i-v506/model-0060.params --lr 0.01 --num-epoch 15 --lr-step 5 --confuse-all
# done
ver=604
for i in $(seq 0 9); do
  scripts/sigr python -m sigr.app inter --log log --snapshot model --root .cache/sigr-inter-tzeng-$i-v$ver --fold $i --batch-size 1000 --num-pixel 2 --num-filter 16 --tzeng --subject-loss-weight 0.1 --subject-confusion-loss-weight 1 --lambda-scale 1 --num-subject-block 0 --params .cache/sigr-inter-$i-v411/model-0060.params --lr 0.01 --num-epoch 15 --lr-step 5 --confuse-conv
done
ver=605
for i in $(seq 0 9); do
  scripts/sigr python -m sigr.app inter --log log --snapshot model --root .cache/sigr-inter-tzeng-$i-v$ver --fold $i --batch-size 1000 --num-pixel 2 --num-filter 16 --tzeng --subject-loss-weight 0.1 --subject-confusion-loss-weight 1 --lambda-scale 1 --num-subject-block 0 --params .cache/sigr-inter-$i-v411/model-0060.params --lr 0.01 --num-epoch 15 --lr-step 5 --confuse-all
done
