#!/usr/bin/env bash

ver=528
for i in $(seq 0 9); do
  scripts/sigr python -m sigr.app inter --gpu 0 --gpu 1 --log log --snapshot model --root .cache/sigr-inter-tzeng-$i-v$ver --fold $i --batch-size 2000 --num-pixel 2 --num-filter 16 --tzeng --subject-loss-weight 0.01 --subject-confusion-loss-weight 1 --lambda-scale 1 --num-subject-block 0 --confuse-all
done
ver=529
for i in $(seq 0 9); do
  scripts/sigr python -m sigr.app inter --gpu 0 --gpu 1 --log log --snapshot model --root .cache/sigr-inter-adabn-tzeng-$i-v$ver --fold $i --adabn --batch-size 1800 --num-pixel 2 --num-filter 16 --tzeng --subject-loss-weight 0.01 --subject-confusion-loss-weight 1 --lambda-scale 1 --num-subject-block 0 --minibatch --confuse-all
done
